### ISSUE TITLE
AWS EKS - Error: cluster doesn't provide client-ca-file

### ISSUE THREAD

**Issue by natefox** [DirectXMan12/k8s-prometheus-adapter#108]
Running a brand new EKS cluster in AWS (platform eks.2 - now with actual HPA!). 
Using kubectl v1.11.2

I get this from the logs (bearer token and cert have been munged):
```
$ kubectl logs custom-metrics-apiserver-f7fb545fc-bf4tt -n custom-metrics
I0906 00:05:22.546046       1 round_trippers.go:386] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: adapter/v0.0.0 (linux/amd64) kubernetes/$Format" -H "Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IiJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJjdXN0b20tbWV0cmljcyIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJjdXN0b20tbWV0cmljcy1hcGlzZXJ2ZXItdG9rZW4tc2o4Y2siLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiY3VzdG9tLW1ldHJpY3MtYXBpc2VydmVyIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291WE0ZTk3NGItYjE2Ni0xMWU4LWEwYWItMDI5NTM5OWI5OTE4Iiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OmN1c3RvbS1tZXRyaWNzOmN1c3RvbS1tZXRyaWNzLWFwaXNlcnZlciJ9.vPapLF7xgD2ajC_o-zhrlOh6DVDATbOwP_HAGDAOP3JyCTbGf9CB2UxJvKAAfiw3pOPMVSQLmoIzpk7zNlEERxN7pJT8ujFfVsfy3gHmXdUNuKXwK773wgnd1ql_1r8UjdgHxNom2qBnukQFJ7hZe5ixUkvHDXskgSz2fZdYOhS0J4Gbg3-26X-bQYdy1xA6FCB1GE0uAsDUhZSlJXR37wiOIyKbK6QV4f_Wmtr1bF89ssXKP_S159ibz9jjmG-nA85qxdAu5FdOYDO4FiYetJhbEPCuLda6BDwiz2vpVL2QPXYl22y7zCnW4VEvNcUBFQTXTyHIoxy_l6zMW0ZjIA" 'https://10.100.0.1:443/api/v1/namespaces/kube-system/configmaps/extension-apiserver-authentication'
I0906 00:05:22.562592       1 round_trippers.go:405] GET https://10.100.0.1:443/api/v1/namespaces/kube-system/configmaps/extension-apiserver-authentication 200 OK in 16 milliseconds
I0906 00:05:22.562668       1 round_trippers.go:411] Response Headers:
I0906 00:05:22.562692       1 round_trippers.go:414]     Content-Type: application/json
I0906 00:05:22.562711       1 round_trippers.go:414]     Content-Length: 1634
I0906 00:05:22.562771       1 round_trippers.go:414]     Date: Thu, 06 Sep 2018 00:05:22 GMT
I0906 00:05:22.563330       1 request.go:897] Response Body: {"kind":"ConfigMap","apiVersion":"v1","metadata":{"name":"extension-apiserver-authentication","namespace":"kube-system","selfLink":"/api/v1/namespaces/kube-system/configmaps/extension-apiserver-authentication","uid":"c7767723-b062-11e8-a0ab-0295399b9918","resourceVersion":"43","creationTimestamp":"2018-09-04T16:51:33Z"},"data":{"requestheader-allowed-names":"[\"front-proxy-client\"]","requestheader-client-ca-file":"-----BEGIN CERTIFICATE-----\nMIICyDCCAbCgAwIBAgIBADANBgkqhkiG9w0BAQsFADAVMRMwEQYDVQQDEwprdWJl\ncm5ldGVzMB4XDTE4MDkwNDE2NTEwMFoXDTI4MDkwMTE2NTEwMFowFTETMBEGA1UE\nAxMKa3ViZXJuZXRlczCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMDw\n38+OPNyv87pqmwdlj4WAsd/p53hR2T8rS9eZEsJ28jzmoAYm6Y2tpMZBENubniAa\nqEWq97CBO+mK41jIB0QZfe1UAgcrY7paeZXvSbXkew10XlJAtAx/Yb5wEd5hJHbS\nXNVhFjHiext/2Zt0wH3G4rdTdILDg0DIVig8o1NSDeA5kiehT/7Jo+9DrSxrY5k1\nAoS1Iy+rzyCmYKoEfzk3Ak6/IphSm1sgE3KPJkljnUdzg1m7fvdFAiczgDTWscDZ\nTvab2DdjnHJ29IvC+/GOrs98+MY2UrK44dd7Z+twVuVZbFAOx3xLd5K/oj3lFjFq\nigCbMwrA42hTiLO2ARsCAwEAAaMjMCEwDgYDVR0PAQH/BAQDAgKkMA8GA1UdEwEB\n/wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEBAKqhu00d0oLKu8TfDq6lZ8fGLig/\nLfNUxI6iTj4LT7uJB4g5aHBDvLiyA+VgVqN2Pb4hWkHQLl8v1b/nOOOMC/36dcDK\nUlsOR4RFR0SQz9xvq7rQVgWaP6v+XATsnamNlPTFtNc0EYNfkuEhpAgodOkhvJF+\n+0MqLP9gyNgmHBd5SR+RrUfYadg85Oae9qVeQpWtDDFmPiZ95AFh5SS9\nAnFBvTwXFZs7wjQiSNaUpt2PimqR9yBgya8dAoBJoDwzjGf8sizqqIX36vapWgVb\naX4CaOIiqornErF0c1uW5J7/sJ7bKg7KDcNGBjJs2aoX0vKda2D6UeA+GOM=\n-----END CERTIFICATE-----\n","requestheader-extra-headers-prefix":"[\"X-Remote-Extra-\"]","requestheader-group-headers":"[\"X-Remote-Group\"]","requestheader-username-headers":"[\"X-Remote-User\"]"}}
Error: cluster doesn't provide client-ca-file
Usage:
   [flags]

Flags:
      --alsologtostderr                                         log to standard error as well as files
      --authentication-kubeconfig string                        kubeconfig file pointing at the 'core' kubernetes server with enough rights to create tokenaccessreviews.authentication.k8s.io.
      --authentication-skip-lookup                              If false, the authentication-kubeconfig will be used to lookup missing authentication configuration from the cluster.
      --authentication-token-webhook-cache-ttl duration         The duration to cache responses from the webhook token authenticator. (default 10s)
      --authorization-kubeconfig string                         kubeconfig file pointing at the 'core' kubernetes server with enough rights to create  subjectaccessreviews.authorization.k8s.io.
      --authorization-webhook-cache-authorized-ttl duration     The duration to cache 'authorized' responses from the webhook authorizer. (default 10s)
      --authorization-webhook-cache-unauthorized-ttl duration   The duration to cache 'unauthorized' responses from the webhook authorizer. (default 10s)
      --bind-address ip                                         The IP address on which to listen for the --secure-port port. The associated interface(s) must be reachable by the rest of the cluster, and by CLI/web clients. If blank, all interfaces will be used (0.0.0.0 for all IPv4 interfaces and :: for all IPv6 interfaces). (default 0.0.0.0)
      --cert-dir string                                         The directory where the TLS certs are located. If --tls-cert-file and --tls-private-key-file are provided, this flag will be ignored. (default "apiserver.local.config/certificates")
      --client-ca-file string                                   If set, any request presenting a client certificate signed by one of the authorities in the client-ca-file is authenticated with an identity corresponding to the CommonName of the client certificate.
      --config string                                           Configuration file containing details of how to transform between Prometheus metrics and custom metrics API resources
      --contention-profiling                                    Enable lock contention profiling, if profiling is enabled
      --discovery-interval duration                             interval at which to refresh API discovery information
      --enable-swagger-ui                                       Enables swagger ui on the apiserver at /swagger-ui
  -h, --help                                                    help for this command
      --http2-max-streams-per-connection int                    The limit that the server gives to clients for the maximum number of streams in an HTTP/2 connection. Zero means to use golang's default.
      --lister-kubeconfig string                                kubeconfig file pointing at the 'core' kubernetes server with enough rights to list any described objets
      --log-flush-frequency duration                            Maximum number of seconds between log flushes (default 5s)
      --log_backtrace_at traceLocation                          when logging hits line file:N, emit a stack trace (default :0)
      --log_dir string                                          If non-empty, write log files in this directory
      --logtostderr                                             log to standard error instead of files (default true)
      --metrics-relist-interval duration                        interval at which to re-list the set of all available metrics from Prometheus (default 10m0s)
      --profiling                                               Enable profiling via web interface host:port/debug/pprof/ (default true)
      --prometheus-auth-config string                           kubeconfig file used to configure auth when connecting to Prometheus.
      --prometheus-auth-incluster                               use auth details from the in-cluster kubeconfig when connecting to prometheus.
      --prometheus-url string                                   URL for connecting to Prometheus. (default "https://localhost")
      --requestheader-allowed-names strings                     List of client certificate common names to allow to provide usernames in headers specified by --requestheader-username-headers. If empty, any client certificate validated by the authorities in --requestheader-client-ca-file is allowed.
      --requestheader-client-ca-file string                     Root certificate bundle to use to verify client certificates on incoming requests before trusting usernames in headers specified by --requestheader-username-headers. WARNING: generally do not depend on authorization being already done for incoming requests.
      --requestheader-extra-headers-prefix strings              List of request header prefixes to inspect. X-Remote-Extra- is suggested. (default [x-remote-extra-])
      --requestheader-group-headers strings                     List of request headers to inspect for groups. X-Remote-Group is suggested. (default [x-remote-group])
      --requestheader-username-headers strings                  List of request headers to inspect for usernames. X-Remote-User is common. (default [x-remote-user])
      --secure-port int                                         The port on which to serve HTTPS with authentication and authorization. If 0, don't serve HTTPS at all. (default 443)
      --stderrthreshold severity                                logs at or above this threshold go to stderr (default 2)
      --tls-cert-file string                                    File containing the default x509 Certificate for HTTPS. (CA cert, if any, concatenated after server cert). If HTTPS serving is enabled, and --tls-cert-file and --tls-private-key-file are not provided, a self-signed certificate and key are generated for the public address and saved to the directory specified by --cert-dir.
      --tls-cipher-suites strings                               Comma-separated list of cipher suites for the server. If omitted, the default Go cipher suites will be use.  Possible values: TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_RC4_128_SHA,TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_RC4_128_SHA,TLS_RSA_WITH_3DES_EDE_CBC_SHA,TLS_RSA_WITH_AES_128_CBC_SHA,TLS_RSA_WITH_AES_128_CBC_SHA256,TLS_RSA_WITH_AES_128_GCM_SHA256,TLS_RSA_WITH_AES_256_CBC_SHA,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_RC4_128_SHA
      --tls-min-version string                                  Minimum TLS version supported. Possible values: VersionTLS10, VersionTLS11, VersionTLS12
      --tls-private-key-file string                             File containing the default x509 private key matching --tls-cert-file.
      --tls-sni-cert-key namedCertKey                           A pair of x509 certificate and private key file paths, optionally suffixed with a list of domain patterns which are fully qualified domain names, possibly with prefixed wildcard segments. If no domain patterns are provided, the names of the certificate are extracted. Non-wildcard matches trump over wildcard matches, explicit domain patterns trump over extracted names. For multiple key/certificate pairs, use the --tls-sni-cert-key multiple times. Examples: "example.crt,example.key" or "foo.crt,foo.key:*.foo.com,foo.com". (default [])
  -v, --v Level                                                 log level for V logs (default 0)
      --vmodule moduleSpec                                      comma-separated list of pattern=N settings for file-filtered logging

panic: cluster doesn't provide client-ca-file

goroutine 1 [running]:
main.main()
	/go/src/github.com/directxman12/k8s-prometheus-adapter/cmd/adapter/adapter.go:41 +0x13b
```

Of note I tried compiling and running the custom-metrics sample server and got the same error. 

Wondering if it's the heptio-iam-authentication that is required to talk to the API Server?

**Comment by DirectXMan12** [comment]
It's due to an "issue" recently fixed in the core kubernetes libraries.  I need to rebase again to pick up the fix (it's the same reason why EKS just now started supporting HPA, hence the articles).

**Comment by ivelichkovich** [comment]
ETA on this fix?

**Comment by DirectXMan12** [comment]
let me do it now

**Comment by DirectXMan12** [comment]
Please test https://github.com/DirectXMan12/k8s-prometheus-adapter/pull/110 to see if it fixes your issue (it should, just want to double-check)

**Comment by nnadig-ebsco** [comment]
@DirectXMan12 thanks for fixing this but how do I test the #110 ? I am using the deployment manifest files for prom-adapter which uses image: directxman12/k8s-prometheus-adapter-amd64:latest
Please suggest.

**Comment by DirectXMan12** [comment]
@nnadig-ebsco I've pushed a fix for the dependency (jsoniter) issue.

The `sed` issue is because OSX ships a BSD sed by default.  Getting compatibility is tricky (see https://stackoverflow.com/questions/16745988/sed-command-with-i-option-in-place-editing-works-fine-on-ubuntu-but-not-mac).  There's a fix that should work, but in light of the below tmp-dir issue, I'm tempted to suggest that people build on Linux in the mean time.

As for the temp dir issue, that seems to be because Docker for Mac is a bit of a hack.  Namely, our docker-build commands assume that the temporary directory is on the same system as the daemon running the build.  This isn't the case in Docker for Mac (it runs in a VM, but tries to hide that from the user).  Manually specifying a directory isn't a good fix, because we can't assume that non-temp directories are writable (e.g. I run my docker builds with source code mounted read-only from another machine).

**Comment by DirectXMan12** [comment]
We could maybe use multi-image dockerfiles, but I'm not certain how many people are running a sufficiently new version of docker to support that.

**Comment by bhavin192** [comment]
I faced this issue recently. I will try to build and test the PR #110

**Comment by bhavin192** [comment]
@nnadig-ebsco Can you please try this image with tag `pr110`
https://hub.docker.com/r/bhavin192/k8s-prometheus-adapter-amd64/tags/
