### ISSUE TITLE
"http2: stream closed" and panic in k8s-prometheus-adapter

### ISSUE THREAD

**Issue by oboguev** [DirectXMan12/k8s-prometheus-adapter#276]
I encountered two issues trying to run quay.io/coreos/k8s-prometheus-adapter-amd64:v0.6.0.

Issue 1:
========

I deployed k8s-prometheus-adapter and observe it reporting the following errors:

>E0306 03:43:30.975425       1 writers.go:163] apiserver was unable to write a JSON response: http2: stream closed
>E0306 03:43:30.975804       1 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"http2: stream closed"}

Although custom metrics was provided to /apis/custom.metrics.k8s.io and observed there, but these errors were going non-stop anyway all the time.

Issue 2:
========

After I undeployed and redeployed an application providing metrics endpoint, k8s-prometheus-adapter went haywire and generates non-stop error messages of the following kind:

>E0306 05:56:49.517943       1 wrap.go:32] apiserver panic'd on GET /apis/custom.metrics.k8s.io/v1beta1
>E0306 05:56:47.818553       1 runtime.go:73] Observed a panic: &errors.errorString{s:"killing connection/stream because serving request timed out and response had been started"} (killing connection/stream because serving request timed out and response had been started)
>goroutine 51985 [running]:
>github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apimachinery/pkg/util/runtime.logPanic(0x15e09e0, 0xc0003d3140)
>        /go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:69 +0x7b
>github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0xc0056b0c98, 0x1, 0x1)
>        /go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51 +0x82
>panic(0x15e09e0, 0xc0003d3140)
>        /usr/local/go/src/runtime/panic.go:679 +0x1b2
>github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/filters.(*baseTimeoutWriter).timeout(0xc000916640, 0xc0066c9680)
>        /go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:256 +0x1cf
>github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP(0xc000311740, 0x1aa92c0, 0xc00012fc00, 0xc0038bdd00)
>        /go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:140 +0x310
>github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/filters.WithWaitGroup.func1(0x1aa92c0, 0xc00012fc00, 0xc0038bdc00)
>        /go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/filters/waitgroup.go:47 +0x10f
>net/http.HandlerFunc.ServeHTTP(0xc00052c5a0, 0x1aa92c0, 0xc00012fc00, 0xc0038bdc00)
>        /usr/local/go/src/net/http/server.go:2007 +0x44
>github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithRequestInfo.func1(0x1aa92c0, 0xc00012fc00, 0xc0038bdb00)
>        /go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/filters/requestinfo.go:39 +0x274
>net/http.HandlerFunc.ServeHTTP(0xc00052c600, 0x1aa92c0, 0xc00012fc00, 0xc0038bdb00)
>        /usr/local/go/src/net/http/server.go:2007 +0x44
>github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/filters.withPanicRecovery.func1(0x1aa92c0, 0xc00012fc00, 0xc0038bdb00)
>        /go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/filters/wrap.go:46 +0x18c
>net/http.HandlerFunc.ServeHTTP(0xc000311760, 0x1a9e300, 0xc0005c23e0, 0xc0038bdb00)
>        /usr/local/go/src/net/http/server.go:2007 +0x44
>github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server.(*APIServerHandler).ServeHTTP(0xc00052c630, 0x1a9e300, 0xc0005c23e0, 0xc0038bdb00)
>        /go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/handler.go:189 +0x51
>net/http.serverHandler.ServeHTTP(0xc00051cee0, 0x1a9e300, 0xc0005c23e0, 0xc0038bdb00)
>        /usr/local/go/src/net/http/server.go:2802 +0xa4
>net/http.initNPNRequest.ServeHTTP(0x1ab1c40, 0xc0006f4720, 0xc0007c2000, 0xc00051cee0, 0x1a9e300, 0xc0005c23e0, 0xc0038bdb00)
>        /usr/local/go/src/net/http/server.go:3366 +0x8d
>github.com/directxman12/k8s-prometheus-adapter/vendor/golang.org/x/net/http2.(*serverConn).runHandler(0xc0003d8a80, 0xc0005c23e0, 0xc0038bdb00, 0xc0009165c0)
>        /go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/golang.org/x/net/http2/server.go:2125 +0x9f
>created by github.com/directxman12/k8s-prometheus-adapter/vendor/golang.org/x/net/http2.(*serverConn).processHeaders
>        /go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/golang.org/x/net/http2/server.go:1859 +0x4eb

API endpoint for custom.metrics.k8s.io/v1beta1 also went down:

>$ kubectl get --raw /apis/custom.metrics.k8s.io/v1beta1
>Error from server (ServiceUnavailable): the server is currently unable to handle the request

although it would come back once in a while shortly (and provide some metadata, but not for custom metrics) but then go down again.

>$ kubectl version
>Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
>Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3+k3s1", GitCommit:"5b17a175ce333dfb98cb8391afeb1f34219d9275", GitTreeState:"clean", BuildDate:"2020-02-27T07:28:53Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

There is nothing particularly remarkable in other pod logs, including metrics-server, although prometheus issued startup warning messages:

>level=warn caller=klog.go:86 component=k8s_client_runtime func=Warningf msg="/app/discovery/kubernetes/kubernetes.go:261: watch of *v1.Endpoints ended with: too old resource version: 10928 (11342)"
>level=warn caller=klog.go:86 component=k8s_client_runtime func=Warningf msg="/app/discovery/kubernetes/kubernetes.go:261: watch of *v1.Endpoints ended with: too old resource version: 17416 (17613)"

but then everything worked fine for a while.

**Comment by GMartinez-Sisti** [comment]
I started having this issue with v0.6.0 on a kubernetes cluster that was upgraded to 1.16.7, with kubernetes 1.15.6 it worked fine.

**Comment by kirrmann** [comment]
I'm also experiencing issue 1 with 1.16.7 and v0.6.0

```
I0318 16:36:43.332760       1 wrap.go:47] GET /apis/metrics.k8s.io/v1beta1: (945.758µs) 200 [Go-http-client/2.0 100.96.0.0:13016]
I0318 16:36:43.335362       1 wrap.go:47] GET /apis/metrics.k8s.io/v1beta1: (680.425µs) 200 [Go-http-client/2.0 100.96.0.0:13016]
E0318 16:36:43.436046       1 writers.go:163] apiserver was unable to write a JSON response: http2: stream closed
E0318 16:36:43.436076       1 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"http2: stream closed"}
E0318 16:36:43.436166       1 writers.go:163] apiserver was unable to write a JSON response: http2: stream closed
E0318 16:36:43.436241       1 writers.go:163] apiserver was unable to write a JSON response: http2: stream closed
I0318 16:37:01.589410       1 wrap.go:47] GET /healthz: (124.917µs) 200 [kube-probe/1.16 100.96.6.1:33530]
E0318 16:36:43.436253       1 writers.go:163] apiserver was unable to write a JSON response: http2: stream closed
I0318 16:36:43.437918       1 wrap.go:47] GET /apis/custom.metrics.k8s.io/v1beta1: (101.81011ms) 200 [Go-http-client/2.0 100.96.0.0:13016]
E0318 16:36:43.447970       1 writers.go:163] apiserver was unable to write a JSON response: http2: stream closed
E0318 16:36:43.448110       1 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"http2: stream closed"}
I0318 16:36:43.449319       1 wrap.go:47] GET /apis/custom.metrics.k8s.io/v1beta1: (123.555347ms) 200 [Go-http-client/2.0 100.96.0.0:13016]
E0318 16:36:43.450306       1 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"http2: stream closed"}
E0318 16:36:43.455273       1 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"http2: stream closed"}
E0318 16:36:43.456353       1 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"http2: stream closed"}
```

**Comment by johanneswuerbach** [comment]
Maybe this is related to https://github.com/kubernetes/kubernetes/pull/82146, which has been released in 1.16?

**Comment by eyalzek** [comment]
I'm getting the same with v0.6.0 on kubernetes v1.15.9.

```
E0402 13:21:01.406204       1 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"http2: stream closed"}
E0402 13:21:16.736407       1 writers.go:163] apiserver was unable to write a JSON response: http2: stream closed
E0402 13:21:16.736548       1 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"http2: stream closed"}
E0402 13:21:20.000342       1 writers.go:163] apiserver was unable to write a JSON response: http2: stream closed
E0402 13:21:20.000398       1 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"http2: stream closed"}
E0402 13:21:50.007662       1 writers.go:163] apiserver was unable to write a JSON response: http2: stream closed
```

**Comment by stafot** [comment]
For me the log flood started after upgrading from `AWS EKS 1.14`  to `1.15` with `0.4.1` apiserver. Problem persists in `0.5.0` and `0.6.0` apiservers too. I am a bit worried if this going to break totally on `1.16` ref. https://github.com/coreos/kube-prometheus/issues/383

**Comment by stafot** [comment]
After upgrading to `AWS EKS 1.16` errors persist, but the amount is smaller.
