### ISSUE TITLE
apiserver panic'd on GET /apis/custom.metrics.k8s.io/v1beta1

### ISSUE THREAD

**Issue by dobesv** [DirectXMan12/k8s-prometheus-adapter#331]
I've been seeing this error on a regular basis in the logs, but I'm not sure what the root cause might be.  It seems like at the very least it should be able to catch the error and log something less scary.

```
E1102 19:28:49.894136       1 wrap.go:39] apiserver panic'd on GET /apis/custom.metrics.k8s.io/v1beta1
I1102 19:28:49.894213       1 log.go:172] http2: panic serving 100.101.77.64:26729: runtime error: invalid memory address or nil pointer dereference
goroutine 12429387 [running]:
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP.func1.1(0xc008178720)
        /go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:108 +0x107
panic(0x1861b80, 0x2cbc140)
        /usr/local/go/src/runtime/panic.go:679 +0x1b2
compress/gzip.(*Writer).Write(0xc0010140b0, 0xc01b466000, 0x71, 0x71, 0x30, 0x1926540, 0xc02a404d01)
        /usr/local/go/src/compress/gzip/gzip.go:168 +0x237
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters.(*deferredResponseWriter).Write(0xc00107f090, 0xc01b466000, 0x71, 0x71, 0xc01b466000, 
0x71, 0x71)
        /go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/writers.go:182 +0x54e
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters.SerializeObject(0x1ab94aa, 0x10, 0x7faaaf9a97c8, 0xc0052890e0, 0x7faaaf9a9718, 0xc0000
c5470, 0xc008e91e00, 0xc8, 0x1d75180, 0xc00107efa0)
        /go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/writers.go:117 +0x389
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters.WriteObjectNegotiated(0x1d94fc0, 0xc00035c9c0, 0x1d95200, 0x2cfcd78, 0x0, 0x0, 0x0, 0x
0, 0x7faaaf9a9718, 0xc0000c5470, ...)
        /go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/writers.go:251 +0x555
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/discovery.(*APIVersionHandler).ServeHTTP(0xc0005c4780, 0x7faaaf9a9718, 0xc0000c5470, 0xc008e91e00)
        /go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/discovery/version.go:81 +0x18f
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/discovery.(*APIVersionHandler).handle(...)
        /go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/discovery/version.go:77
github.com/directxman12/k8s-prometheus-adapter/vendor/github.com/emicklei/go-restful.(*Container).dispatch(0xc000830090, 0x7faaaf9a9718, 0xc0000c5470, 0xc008e91e00)
        /go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/github.com/emicklei/go-restful/container.go:288 +0xa4f
github.com/directxman12/k8s-prometheus-adapter/vendor/github.com/emicklei/go-restful.(*Container).Dispatch(...)
        /go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/github.com/emicklei/go-restful/container.go:199
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server.director.ServeHTTP(0x1ac73ea, 0x1a, 0xc000830090, 0xc000112cb0, 0x7faaaf9a9718, 0xc0000c5470, 0xc008e91e00)
        /go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/handler.go:146 +0x4d3
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithAuthorization.func1(0x7faaaf9a9718, 0xc0000c5470, 0xc008e91e00)
        /go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/filters/authorization.go:64 +0x512
net/http.HandlerFunc.ServeHTTP(0xc00023a380, 0x7faaaf9a9718, 0xc0000c5470, 0xc008e91e00)
        /usr/local/go/src/net/http/server.go:2007 +0x44
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/filters.WithMaxInFlightLimit.func1(0x7faaaf9a9718, 0xc0000c5470, 0xc008e91e00)
        /go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/filters/maxinflight.go:160 +0x5dc
net/http.HandlerFunc.ServeHTTP(0xc00048e1e0, 0x7faaaf9a9718, 0xc0000c5470, 0xc008e91e00)
        /usr/local/go/src/net/http/server.go:2007 +0x44
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithImpersonation.func1(0x7faaaf9a9718, 0xc0000c5470, 0xc008e91e00)
        /go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/filters/impersonation.go:50 +0x1fe6
net/http.HandlerFunc.ServeHTTP(0xc00023a3c0, 0x7faaaf9a9718, 0xc0000c5470, 0xc008e91e00)
        /usr/local/go/src/net/http/server.go:2007 +0x44
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithAuthentication.func1(0x7faaaf9a9718, 0xc0000c5470, 0xc008e91d00)
        /go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/filters/authentication.go:131 +0xa8c
net/http.HandlerFunc.ServeHTTP(0xc000035860, 0x7faaaf9a9718, 0xc0000c5470, 0xc008e91d00)
        /usr/local/go/src/net/http/server.go:2007 +0x44
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP.func1(0xc008178720, 0xc000782580, 0x1d9e200, 0xc0000c5470, 0xc008e91d00)
        /go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:113 +0xd0
created by github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP
        /go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:99 +0x1cb


goroutine 12429409 [running]:
github.com/directxman12/k8s-prometheus-adapter/vendor/golang.org/x/net/http2.(*serverConn).runHandler.func1(0xc0027acdd8, 0xc0010bbf67, 0xc001abe300)
        /go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/golang.org/x/net/http2/server.go:2142 +0x16b
panic(0x17cd020, 0xc0221cccf0)
        /usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0xc0010bbc90, 0x1, 0x1)
        /go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:55 +0x105
panic(0x17cd020, 0xc0221cccf0)
        /usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP(0xc000782580, 0x1d93180, 0xc01d343730, 0xc008e91d00)
        /go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:119 +0x486
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/filters.WithWaitGroup.func1(0x1d93180, 0xc01d343730, 0xc008e91c00)
        /go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/filters/waitgroup.go:47 +0x10f
net/http.HandlerFunc.ServeHTTP(0xc00048e210, 0x1d93180, 0xc01d343730, 0xc008e91c00)
        /usr/local/go/src/net/http/server.go:2007 +0x44
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithRequestInfo.func1(0x1d93180, 0xc01d343730, 0xc008e91b00)
        /go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/filters/requestinfo.go:39 +0x274
net/http.HandlerFunc.ServeHTTP(0xc00048e240, 0x1d93180, 0xc01d343730, 0xc008e91b00)
        /usr/local/go/src/net/http/server.go:2007 +0x44
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/httplog.WithLogging.func1(0x1d87100, 0xc0027acdd8, 0xc0121fe900)
        /go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:89 +0x2ca
net/http.HandlerFunc.ServeHTTP(0xc0007825a0, 0x1d87100, 0xc0027acdd8, 0xc0121fe900)
        /usr/local/go/src/net/http/server.go:2007 +0x44
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/filters.withPanicRecovery.func1(0x1d87100, 0xc0027acdd8, 0xc0121fe900)
        /go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/filters/wrap.go:51 +0x13e
net/http.HandlerFunc.ServeHTTP(0xc0007825c0, 0x1d87100, 0xc0027acdd8, 0xc0121fe900)
        /usr/local/go/src/net/http/server.go:2007 +0x44
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server.(*APIServerHandler).ServeHTTP(0xc00048e270, 0x1d87100, 0xc0027acdd8, 0xc0121fe900)
        /go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/handler.go:189 +0x51
net/http.serverHandler.ServeHTTP(0xc0002eafc0, 0x1d87100, 0xc0027acdd8, 0xc0121fe900)
        /usr/local/go/src/net/http/server.go:2802 +0xa4
net/http.initNPNRequest.ServeHTTP(0x1d9ddc0, 0xc0088c8420, 0xc0007c7500, 0xc0002eafc0, 0x1d87100, 0xc0027acdd8, 0xc0121fe900)
        /usr/local/go/src/net/http/server.go:3366 +0x8d
github.com/directxman12/k8s-prometheus-adapter/vendor/golang.org/x/net/http2.(*serverConn).runHandler(0xc001abe300, 0xc0027acdd8, 0xc0121fe900, 0xc01fac3d40)
        /go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/golang.org/x/net/http2/server.go:2149 +0x9f
created by github.com/directxman12/k8s-prometheus-adapter/vendor/golang.org/x/net/http2.(*serverConn).processHeaders
        /go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/golang.org/x/net/http2/server.go:1883 +0x4eb
E1102 19:28:49.895165       1 writers.go:118] apiserver was unable to write a fallback JSON response: http2: stream closed
```

**Comment by dobesv** [comment]
Here's a gist with all the kubernetes YAML files:

https://gist.github.com/dobesv/24a5f81bddd1a7008135f3763abec4d5

**Comment by dobesv** [comment]
It's version `0.7.0`

**Comment by dobesv** [comment]
If I update to version `v0.8.1` I get the error mentioned in https://github.com/DirectXMan12/k8s-prometheus-adapter/issues/329

**Comment by timClicks** [comment]
This affects me too. It brings down the API endpoint.

```console
$ kubectl get --raw /apis/custom.metrics.k8s.io/v1beta1
Error from server (ServiceUnavailable): the server is currently unable to handle the request
```

**Comment by s-urbaniak** [comment]
This should be fixed in #335

**Comment by fractos** [comment]
Hi, still seeing this in v0.8.2:

```I1222 23:51:37.570679       1 httplog.go:89] "HTTP" verb="GET" URI="/apis/custom.metrics.k8s.io/v1beta1" latency="17.696874ms" userAgent="Go-http-client/2.0" srcIP="10.0.88.110:45980" resp=200
E1222 23:51:37.570761       1 runtime.go:76] Observed a panic: runtime error: invalid memory address or nil pointer dereference
goroutine 487 [running]:
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP.func1.1(0xc004476660)
        /go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:108 +0x107
panic(0x1aa1b60, 0x3189600)
        /usr/local/go/src/runtime/panic.go:679 +0x1b2
compress/gzip.(*Writer).Write(0xc000271810, 0xc004687200, 0x71, 0x71, 0x30, 0x1b79a80, 0xc005360c01)
        /usr/local/go/src/compress/gzip/gzip.go:168 +0x237
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters.(*deferredResponseWriter).Write(0xc0005ac640, 0xc004687200, 0x71, 0x71, 0xc004687200, 0x71, 0x71)
        /go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/writers.go:182 +0x54e
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters.SerializeObject(0x1d35b02, 0x10, 0x7fdf29c8af98, 0xc00030fc20, 0x7fdf2a1f8198, 0xc00000e0e8, 0xc000574d00, 0xc8, 0x2096640, 0xc0005ac5f0)
        /go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/writers.go:117 +0x389
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters.WriteObjectNegotiated(0x20b9640, 0xc0003f6300, 0x20b98c0, 0x31ce040, 0x0, 0x0, 0x0, 0x0, 0x7fdf2a1f8198, 0xc00000e0e8, ...)
        /go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/writers.go:251 +0x555
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/discovery.(*APIVersionHandler).ServeHTTP(0xc000706440, 0x7fdf2a1f8198, 0xc00000e0e8, 0xc000574d00)
        /go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/discovery/version.go:81 +0x17b
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/discovery.(*APIVersionHandler).handle(...)
        /go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/discovery/version.go:77
github.com/directxman12/k8s-prometheus-adapter/vendor/github.com/emicklei/go-restful.(*Container).dispatch(0xc00064a480, 0x7fdf2a1f8198, 0xc00000e0e8, 0xc000574d00)
        /go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/github.com/emicklei/go-restful/container.go:294 +0x635
github.com/directxman12/k8s-prometheus-adapter/vendor/github.com/emicklei/go-restful.(*Container).Dispatch(...)
        /go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/github.com/emicklei/go-restful/container.go:204
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server.director.ServeHTTP(0x1d44a83, 0x1a, 0xc00064a480, 0xc00036e930, 0x7fdf2a1f8198, 0xc00000e0e8, 0xc000574d00)
        /go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/handler.go:146 +0x531
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithAuthorization.func1(0x7fdf2a1f8198, 0xc00000e0e8, 0xc000574d00)
        /go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/filters/authorization.go:64 +0x548
net/http.HandlerFunc.ServeHTTP(0xc0000a1840, 0x7fdf2a1f8198, 0xc00000e0e8, 0xc000574d00)
        /usr/local/go/src/net/http/server.go:2036 +0x44
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/filters.WithMaxInFlightLimit.func2(0x7fdf2a1f8198, 0xc00000e0e8, 0xc000574d00)
        /go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/filters/maxinflight.go:175 +0x4f6
net/http.HandlerFunc.ServeHTTP(0xc001a0f3b0, 0x7fdf2a1f8198, 0xc00000e0e8, 0xc000574d00)
        /usr/local/go/src/net/http/server.go:2036 +0x44
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithImpersonation.func1(0x7fdf2a1f8198, 0xc00000e0e8, 0xc000574d00)
        /go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/filters/impersonation.go:50 +0x22f3
net/http.HandlerFunc.ServeHTTP(0xc0000a1880, 0x7fdf2a1f8198, 0xc00000e0e8, 0xc000574d00)
        /usr/local/go/src/net/http/server.go:2036 +0x44
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithAuthentication.func1(0x7fdf2a1f8198, 0xc00000e0e8, 0xc000574c00)
        /go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/filters/authentication.go:70 +0x5ea
net/http.HandlerFunc.ServeHTTP(0xc0000ebe00, 0x7fdf2a1f8198, 0xc00000e0e8, 0xc000574c00)
        /usr/local/go/src/net/http/server.go:2036 +0x44
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP.func1(0xc004476660, 0xc001a135c0, 0x20c3800, 0xc00000e0e8, 0xc000574c00)
        /go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:113 +0xd0
created by github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP
        /go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:99 +0x1cb```

**Comment by fractos** [comment]
@s-urbaniak Hi, should I open this as a fresh issue?
