### ISSUE TITLE
Panics in logs are overly verbose

### ISSUE THREAD

**Issue by tcolgate** [DirectXMan12/k8s-prometheus-adapter#343]
We're seeing one of our k8s-prometheus-adapter instances throwing frequent panics.
```
E1201 08:05:35.092180       1 writers.go:105] apiserver was unable to write a JSON response: http2: stream closed
E1201 08:05:35.092891       1 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"http2: stream closed"}
E1201 08:05:35.092308       1 writers.go:105] apiserver was unable to write a JSON response: http2: stream closed
E1201 08:05:35.092334       1 writers.go:105] apiserver was unable to write a JSON response: http2: stream closed
E1201 08:05:35.094257       1 runtime.go:76] Observed a panic: runtime error: invalid memory address or nil pointer dereference
goroutine 3420 [running]:
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP.func1.1(0xc000513620)
        /go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:108 +0x107
panic(0x1aa1b60, 0x3189600)
        /usr/local/go/src/runtime/panic.go:679 +0x1b2
compress/gzip.(*Writer).Write(0xc00086afd0, 0xc000a82680, 0x71, 0x71, 0x30, 0x1b79a80, 0xc000822c01)
        /usr/local/go/src/compress/gzip/gzip.go:168 +0x237
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters.(*deferredResponseWriter).Write(0xc0000dd950, 0xc000a82680, 0x71, 0x71, 0xc000a82680, 0x71, 0x71)
        /go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/writers.go:182 +0x54e
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters.SerializeObject(0x1d35b02, 0x10, 0x7f4c6b9f27b8, 0xc0009fe640, 0x7f4c6b99d460, 0xc00047c368, 0xc000622b00, 0xc8, 0x2096640, 0xc0000dd900)
....
```
This appears to be due to the server having gone away waiting for the response. The actual response time issue is unfortunate, and I need to investigate further however  they probably don't warrant a full go routine stack dump. I'm getting 90 lines of logs for each incident, which makes any other underlying issues harder to spot.

**Comment by tcolgate** [comment]
So, turns out that the particular panic was caused by an attempt to write to a closed socket, that was happening because I had a TCP health check configured. I've switch to using /livez and /readyz and things look better
